substitutions:
  name: esp-pool-v2
  friendly_name: esp-pool-v2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://Lere-q/dallas-patched
    components: [dallas_patched]
    refresh: 0s

logger:

api:
  encryption:
    key: "BG4fJUKqFmPL3ozj4svfVH7UC8CY8bN1So14EZOQrKc="

ota:
  - platform: esphome
    password: "dbf0fff38d82c8bcf266180cd9de3b78"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp-Pool-V2 Fallback Hotspot"
    password: "nefphcfzwYjo"

captive_portal:

sensor:
  - platform: dallas_patched
    pin:
      number: 16
      mode: input_pullup
    name: "Temperatur"
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    update_interval: 15s
    filters:
      - moving_average:
          window_size: 3
          send_every: 1
