substitutions:
  name: esp-pool-v2
  friendly_name: esp-pool-v2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

external_components:
  - source: github://Lere-q/dallas-patched
    components: [dallas_patched]

logger:

api:
  encryption:
    key: "DEIN_API_KEY"

ota:
  - platform: esphome
    password: "DEIN_OTA_PASS"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Esp-Pool-V2 Fallback"
    password: "DEIN_FALLBACK_PASS"

captive_portal:

sensor:
  - platform: dallas_patched
    pin:
      number: 16
      mode: input_pullup
    name: "Temperatur"
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    device_class: temperature
    state_class: measurement
    update_interval: 15s
